// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0b_WjugxQTUoq6Dztlhpj0Ei4za1egmw',
    appId: '1:169451032431:web:d8e35cf81434914c62c9bf',
    messagingSenderId: '169451032431',
    projectId: 'starry-science-jxfb9',
    authDomain: 'starry-science-jxfb9.firebaseapp.com',
    storageBucket: 'starry-science-jxfb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0b_WjugxQTUoq6Dztlhpj0Ei4za1egmw',
    appId: '1:169451032431:android:e154fcfdf05c21dfd9a0d8',
    messagingSenderId: '169451032431',
    projectId: 'starry-science-jxfb9',
    storageBucket: 'starry-science-jxfb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0b_WjugxQTUoq6Dztlhpj0Ei4za1egmw',
    appId: '1:169451032431:ios:b3f462adfe8084a3d9a0d8',
    messagingSenderId: '169451032431',
    projectId: 'starry-science-jxfb9',
    storageBucket: 'starry-science-jxfb9.firebasestorage.app',
    iosBundleId: 'com.snapsave.downloader.mobileApp',
  );
}
