// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGrd2pyOmibadAMUwCs0Hg4puGKXa9Mw',
    appId: '1:705729241638:web:d717c53239502de3923ce7',
    messagingSenderId: '705729241638',
    projectId: 'rato-aeaac',
    authDomain: 'rato-aeaac.firebaseapp.com',
    databaseURL: 'https://rato-aeaac-default-rtdb.firebaseio.com',
    storageBucket: 'rato-aeaac.firebasestorage.app',
    measurementId: 'G-MGSCSK72QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNVZYUCUYFvVBwvtUst2IUfEd-qjCKZfg',
    appId: '1:705729241638:android:02fe0841c8805ebd923ce7',
    messagingSenderId: '705729241638',
    projectId: 'rato-aeaac',
    databaseURL: 'https://rato-aeaac-default-rtdb.firebaseio.com',
    storageBucket: 'rato-aeaac.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbdqUfU-Ly6rZ_HC1WJFs1NzoN7PF0NJM',
    appId: '1:705729241638:ios:9f14be9dd9fc5e6d923ce7',
    messagingSenderId: '705729241638',
    projectId: 'rato-aeaac',
    databaseURL: 'https://rato-aeaac-default-rtdb.firebaseio.com',
    storageBucket: 'rato-aeaac.firebasestorage.app',
    iosBundleId: 'com.snapsave.downloader.mobileApp',
  );
}
